### ISSUE TITLE
The action pushes pages to the master branch

### ISSUE THREAD

**Issue by njzjz** [JamesIves/github-pages-deploy-action#10]
**Describe the bug**

I am not sure what happened, but I just found the action pushes pages to the master branch.

**Reproduce**

commit: https://github.com/njzjz/chemicaltools-web/commit/3193a2e14116cdadc7317c7992d879e20e34db10
I guess this is the output: https://github.com/njzjz/chemicaltools-web/runs/164561317

**Expected behavior**

The action should never push anything to the master branch.

**Screenshots**

![image](https://user-images.githubusercontent.com/9496702/61396421-4b4ae280-a8fa-11e9-88a6-24eca0c98604.png)

**Additional Comments**

**Comment by JamesIves** [comment]
I've not experienced this before - can you provide your config (minus any secrets)? It should only push to the branch you have set.  Also does this happen consistently or just a one off? I see a push to the `gh-pages` branch since this commit.

I'm wondering if something here failed silently and it continued the process, in which case #9 should fix this.

**Comment by njzjz** [comment]
I think I find the reason. The action makes a commit to the `master` branch although it push the commit to `gh-pages`. Then I run the command `yarn semantic-release` -- it pushes the previous commit to `master`.
![image](https://user-images.githubusercontent.com/9496702/61474631-a0026200-a9bb-11e9-8f12-4b1e6786469f.png)
Maybe swapping their locations can resolve this problem.

**Comment by JamesIves** [comment]
Let me know if you experience this issue again and we can revive this issue!
