### ISSUE TITLE
Custom git config support

### ISSUE THREAD

**Issue by SukkaW** [JamesIves/github-pages-deploy-action#153]
**Is your feature request related to a problem? Please describe.**

I have setup a specific GitHub Account (@sukkabot) used to deploy things to GitHub Pages. I'd like to have deploy commits created by `SukkaBot` in stead of me.

**Describe the solution you'd like**

Travis CI has its own GitHub Pages deployer with [many configurations](https://docs.travis-ci.com/user/deployment/pages/#further-configuration). In this case I want `email` and `name` options being available at  `github-pages-deploy-action`. `GIT_CONFIG_USERNAME` and `GIT_CONFIG_EMAIL` could be added.

**Comment by JamesIves** [comment]
This option was originally available in an earlier version, but since support for the Github Token was added it was removed in favor of the name and email in the commit context object. I think now that there’s support for things such as the deploy token it’s worth having again.

Would you like to PR this? If not I can add it when I get a spare moment.

**Comment by SukkaW** [comment]
@JamesIves Possibly not. I might just wait for a newer release.

**Comment by JamesIves** [comment]
Releases as part of `3.2.1`: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.2.1
