### ISSUE TITLE
Can I support deployment to other repositories?

### ISSUE THREAD

**Issue by rxliuli** [JamesIves/github-pages-deploy-action#21]
Yes, I now have a private repository hosting the blog source files, but deploying github pages is in another repository. Can I support this?

> Thanks a lot for this tool to help me automate the deployment of online documentation for open source projects.

**Comment by JamesIves** [comment]
Your docs are in one repo, but you want to deploy it to another? 

I'd need to have a little bit more context, but I don't see why you couldn't modify the `checkout` step before this action runs to checkout code from another repository. So long as it gets put in the `workspace` folder it should work with anything you decide to put in it.

**Comment by cormacrelf** [comment]
Do you mean:

1. Checkout multiple repositories into the workspace, using the `path` option of `actions/checkout`
2. Move all the files you want to deploy from one part of the workspace to another, making sure you haven't checked out the target repository in such a way that there are still files there that need to be erased
3. ??? Read the entire source code of this action to find out how it works
4. Still not work out what you mean
5. Try random combinations of workspace checkouts, getting GHA to build in full each time

I haven't done step 5 yet but that would be next.

I would note that on the beta3 branch you can simply [provide a `GITHUB_REPOSITORY` environment variable and it will assemble the .git URL with it](https://github.com/JamesIves/github-pages-deploy-action/blob/6a3d30c51db417d43fe6790e51e05fb596bf3944/src/main.ts#L60). One step.

This is a very popular pattern, not just for private repo blogs, but that's the most common. I know travis has had it for years, because it's useful. I use it to publish multiple pages roots from a single repo.
