### ISSUE TITLE
Update token instructions in README

### ISSUE THREAD

**Issue by MichaelCurrin** [JamesIves/github-pages-deploy-action#285]
I see in the README.md that is says this for GITHUB_TOKEN:

> Please note there is currently an issue affecting the use of this token which makes it so it only works with private repositories, you can learn more here.

But the linked issue is #5 is closed and a related PR in other repo seems to be using GITHUB_TOKEN fine. https://github.com/mojira/helper-messages/pull/44/files

Therefore I'd like to suggest that section be updated to reflect the current state.

Also it can be made clearer which one should be used. I found [this](https://github.com/JamesIves/github-pages-deploy-action/blob/3.4.9/action.yml#L15-L21) - it looks like GITHUB_TOKEN is standard but ACCESS_TOKEN may be necessary based on permissions, but it's not clear to me when to use one or the other. Or if it's fine to default to using ACCESS_TOKEN if its safer and has no loss in functionality.

Thanks

**Comment by JamesIves** [comment]
I think that's a fair point, and I agree it. could be made clearer. The GitHub token has had some issues previously where it wouldn't trigger a page re-build on GitHubs end after the deployment was made, meaning it would finish the job but you'd never see the changes reflected on your page. GitHub has updated this I believe but they haven't really communicated that it's fixed or not which is why the README was never updated.

In terms of what should be used, either the GitHub token or the deploy key. If you don't want to generate a deploy key then you _can_ use an access token, but it's essentially like piping your password into the action. Should it ever get exposed in your repository it's the same as exposing your GitHub account credentials. 

I'm happy to make an update to this later today!

**Comment by MichaelCurrin** [comment]
Thanks.

I did some more reading so now I understand as I'd only used Access Token before. I see them as Access Token (generated manually), Github Token (generated by Github), and deploy keys (generated manually with SSH key for a machine). Actually just put together a [guide](https://github.com/MichaelCurrin/cheatsheets/blob/master/cheatsheets/ci_cd/github_actions/tokens/README.md) now.

- It sounds like **GITHUB_TOKEN** is the most convenient as it needs most setup as is already in use by some projects. I see what you mean about the rebuild bug, which you said was fixed by GH but not well communicated.
- **ACCESS_TOKEN** - Hmm sounds like a security risk I hadn't thought about. I thought Github would prevent exposure/logging of this in the output such as by PRs (e.g. from a fork). Or maybe it was a Netlify feature. Either way, I can't find anything about that.

Also a grammar improvement in case this sentence stays after changes:

`the repositories provided GitHub token` => `the repository's provided GitHub token`

**Comment by JamesIves** [comment]
Any secrets that are placed in the secrets menu are automatically hidden from the logs by the action runner. This action also has some redundancy built in for those who use this as a node module instead.

For more information on using a deploy key there's a guide in the README [here](https://github.com/JamesIves/github-pages-deploy-action#using-an-ssh-deploy-key-).

**Comment by MichaelCurrin** [comment]
Okay great, thanks for the info.

I thought the SSH needed to be paired as public and private and the private being on the machine doing the request. 
But it looks like the flow here is create the deploy key which is used for the repo only, then get the SSH action to read that so it can make it available for this GH pages action to use,  with the ssh true flag.

**Comment by JamesIves** [comment]
The README has been updated!

**Comment by MichaelCurrin** [comment]
Thanks!
