### ISSUE TITLE
Request: make minor and patch releases available as specific tags

### ISSUE THREAD

**Issue by Vinnl** [JamesIves/github-pages-deploy-action#324]
**Is your feature request related to a problem? Please describe.**
To avoid the risk of updates to this Action breaking CI builds at an unscheduled time, some people like to pin them to a specific version so they can upgrade to new releases on their own schedule.

Currently, it is only possible to pin to the major version. Doing something like this:

    uses: JamesIves/github-pages-deploy-action@releases/v3.5.5

results in:

    ##[error]An action could not be found at the URI 'https://api.github.com/repos/JamesIves/github-pages-deploy-action/tarball/releases/v3.5.5'

**Describe the solution you'd like**
Individual patch and minor releases to also be published as their own specific tags.

**Additional Comments**

N/A

**Comment by JamesIves** [comment]
You should be able to target any specific version that is released to the marketplace like so: `uses: JamesIves/github-pages-deploy-action@3.5.4` 

![image](https://user-images.githubusercontent.com/10888441/84045324-a48a8d00-a976-11ea-8b6c-5e40dac96fb4.png)

Does that work for your purpose?

**Comment by Vinnl** [comment]
Yeah that's what I did (see initial description), but that resulted in the stated error:

    ##[error]An action could not be found at the URI 'https://api.github.com/repos/JamesIves/github-pages-deploy-action/tarball/releases/v3.5.5'

**Comment by JamesIves** [comment]
In your original post you have `JamesIves/github-pages-deploy-action@releases/v3.5.5`, it needs to be `JamesIves/github-pages-deploy-action@3.5.5`.

**Comment by Vinnl** [comment]
Aaargh. Sorry about that, and thanks for the GH Action.

**Comment by JamesIves** [comment]
No problem! Regardless I'm really not a fan of pointing people to `releases/v3` in the README. GitHub Actions has no version management and I acknowledge that it's super annoying that an update can break thousands of workflows all at once.

I think a good improvement here would be to [expand this script](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/.github/workflows/publish.yml#L29-L32) that runs on version release to also update the version number reference in the README so it points to the current version instead of the `releases/v3` branch. I haven't done this with a README before but I don't see why it wouldn't be possible?
