### ISSUE TITLE
The deploy action hasn't worked in a week

### ISSUE THREAD

**Issue by Zireael07** [JamesIves/github-pages-deploy-action#516]
**Describe the bug**
I have made no changes to the workflow file ever since it started working (see my other issue), but a week ago GitHub Actions stopped "noticing" that there is a deploy action. It only lists the build action, after which it'll spin and spin and spin the yellow circle, and the one action I haven't forcefully stopped earlier "succeeded" 3 days later (as in, there's a green tick, but no deploy)!

**Reproduce**
https://github.com/Zireael07/Rust-HTML-roguelike

**Logs**
https://github.com/Zireael07/Rust-HTML-roguelike/blob/master/.github/workflows/rust.yml

**Additional Comments**
No idea what could be the problem - no outage info/degraded functionality from GH on the day when it started. Restarting the job makes no difference.

**Comment by JamesIves** [comment]
Half of your workflow isn't working, not just this action. If you look at your action runs only `Build` is triggering. Your issue is likely with how your workflow is configured.

I'd start by investigating this: https://github.com/Zireael07/Rust-HTML-roguelike/blob/master/.github/workflows/rust.yml#L31 and changing it from `Build` to `[build]` as it matches your job name.

**Comment by Zireael07** [comment]
It doesn't make sense for this to be working for one week, then suddenly stop working the next week without any workflow changes, though.

**Comment by Zireael07** [comment]
Yep, that worked - but as I said before, it was capitalized before and worked for a week before suddenly not working.... something changed in the way GH parses the workflow file?

**Comment by JamesIves** [comment]
That's possible, but I'd suggest contact GitHub regarding that
