### ISSUE TITLE
Deploy to gh-pages job failing

### ISSUE THREAD

**Issue by SooluThomas** [JamesIves/github-pages-deploy-action#568]
**Describe the bug**

The deploy to gh-pages job is failing with the error
```bash
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 1 ❌
```
I got it to work correctly once after bumping to the latest version but it failed for every job after that. 

**Reproduce**

I'm not sure.

**Logs**

Log - https://github.com/qiskit-community/qiskit-translations/runs/1668532505
link to the yml file - https://github.com/qiskit-community/qiskit-translations/blob/master/.github/workflows/staging-workflow.yml

**Additional Comments**

--

**Comment by JamesIves** [comment]
Looks like it's failing on the initialization step, but that could be due to a number of things. Can you try using the following for `actions/checkout`? It's possible that there's a change on the master branch that is causing problems with your workflow. 

```
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
```

In general pointing an action at branch as opposed to a tagged version is not advised in a production environment.

**Comment by SooluThomas** [comment]
I tried updating the .yml file based on your comments above and the job still errors - https://github.com/qiskit-community/qiskit-translations/runs/1683140668?check_suite_focus=true. It was working fine till the previous release. I had seen the trend of the jobs failing after every new release which is why bumped to the latest version and it failed as well.

**Comment by SooluThomas** [comment]
It worked after a couple of failing builds. Thanks!
