### ISSUE TITLE
error: pathspec 'master' did not match any file(s) known to git

### ISSUE THREAD

**Issue by ccrisan** [JamesIves/github-pages-deploy-action#72]
**Describe the bug**

Deploy fails when trying to checkout master branch:

    error: pathspec 'master' did not match any file(s) known to git

I confirm that the repo is public and the `master` branch actually exists: https://github.com/qtoggle/qui/tree/master.

**Reproduce**

It's a public repo and here's a link to the failed run: https://github.com/qtoggle/qui/runs/332062186.

Does the command run in the correct folder?

**Expected behavior**

The `git checkout master` command should actually checkout the master branch and the deployment should carry on.

**Screenshots**

> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/76639/70097985-62813700-1633-11ea-9ca5-37163e687fd0.png)

**Comment by JamesIves** [comment]
The action will run in the same context as your `package.json` file. This issue seems vaguely familiar, and likely something we've already fixed. Can you try using `releases/v3`? 

Here's the [migration guide](https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.0.0) and a PR I made against your repo: https://github.com/qtoggle/qui/pull/6

**Comment by ccrisan** [comment]
@JamesIves thanks for your help. The solution was indeed to use `releases/v3` as well as preparing the pages in a separate step rather than using `BUILD_SCRIPT`.
