### ISSUE TITLE
Cannot push to newly created gh-pages branch

### ISSUE THREAD

**Issue by JacksonMaxfield** [JamesIves/github-pages-deploy-action#74]
**Description:**

Something is going wrong with the git commands of the releases/v3 action. Specifically I am receiving the following error:

`fatal: invalid reference: origin/gh-pages`

**Context:**
I am slowly getting around to upgrading all my deployments to v3 and encountered an unusual bug. To fully reset everything, I deleted the `gh-pages` branch from my repo and then switched over the deployment code to v3. Commit one [here](https://github.com/openseattle/convictionvacation/commit/929586be66b2bdac8118a8597cc4dedf983a55cb), Commit two [here](https://github.com/openseattle/convictionvacation/commit/7bbda3f2054dd1233ccebb9cbf8beccbb71923e2).

Focusing on the second commit after I had realized I had made a mistake, it produced [this log](https://github.com/openseattle/convictionvacation/commit/7bbda3f2054dd1233ccebb9cbf8beccbb71923e2/checks?check_suite_id=344892182).

Happy to rerun the action or try things on my side just very confused by the bug since it seems to be a git failure but not sure how to solve considering the git command is being run by the `github-pages-deploy-action` itself.

**Comment by fennifith** [comment]
Apologies for potential "me too" spam - I'm also experiencing this beginning, err, today. I'm assuming the issue is related (it might not be, but this is a little too coincidental) - I haven't made any changes to the deployment branch in my repo since it was last working on v3.

[Broken deployment log](https://github.com/HorrificDev/horrific.dev/commit/aac824a71624313dc4c5f04e7eb21eb102ba5f1c/checks?check_suite_id=344724363), in contrast to a previously [working deployment log](https://github.com/HorrificDev/horrific.dev/runs/315229054) from quite a while ago; no configuration changes have happened since then, and only minor modifications have happened within the repo's source code. I'm really confused how this could suddenly start failing on me. Are computers haunted? There aren't any GitHub service outages at the moment... _that I know of..._

My immediate suspicion was the different commit author, but that would probably cause a failure on a git pull/fetch rather than `worktree add` - and [a second attempt](https://github.com/HorrificDev/horrific.dev/runs/336138766) by me resulted in the same error.

**Comment by JamesIves** [comment]
Try changing this line https://github.com/HorrificDev/horrific.dev/blob/master/.github/workflows/deploy.yml#L14 to `actions/checkout@v1`. I just re-ran a deployment in a repository of my own and it passed just fine. 

https://github.com/JamesIves/reddit-viewer/commit/5d7c1d5efcaa8924cd38cab52392c73652a86032/checks?check_suite_id=345013089

**Comment by JacksonMaxfield** [comment]
Wow. Nice catch. @fennifith I just switched to `actions/checkout@v1` and it works for me. Thanks! 🎉

**Comment by fennifith** [comment]
That was it! I was just testing commands locally, coming to the conclusion that something was off with `git fetch` creating branch refs. Thanks a ton for the help @JamesIves!

**Comment by JamesIves** [comment]
I'm glad that worked! I'd love to figure out a way to make this more prominent in the README as I feel it's quite easy to just skip over at the moment.

**Comment by cdaringe** [comment]
:bow: thx guys

**Comment by JamesIves** [comment]
I'm going to pin this issue so it's more visible to others in the same position!
